"""initial_schema

Revision ID: 8e21199856b3
Revises:
Create Date: 2025-09-14 17:35:51.747472

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8e21199856b3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
