"""rename column

Revision ID: cc454f1608f9
Revises: 761456864118
Create Date: 2025-05-19 17:56:25.436873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc454f1608f9"
down_revision: Union[str, None] = "761456864118"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    op.drop_table("hotels")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotels",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('hotels_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("location", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="hotels_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("hotel_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name="rooms_hotel_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="rooms_pkey"),
    )
    # ### end Alembic commands ###
