"""initial migration v3

Revision ID: 71a95a5b10b2
Revises: cb9ddbbb8f94
Create Date: 2025-05-19 15:27:23.596578

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "71a95a5b10b2"
down_revision: Union[str, None] = "cb9ddbbb8f94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
