"""initial migration

Revision ID: 8061f5289c3f
Revises:
Create Date: 2025-05-18 00:42:57.620496

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8061f5289c3f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
