"""initial migration v2

Revision ID: cb9ddbbb8f94
Revises: 8061f5289c3f
Create Date: 2025-05-19 15:24:30.075390

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "cb9ddbbb8f94"
down_revision: Union[str, None] = "8061f5289c3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
